apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auto-shop-ingress
  namespace: auto-shop
  labels:
    app.kubernetes.io/name: auto-shop-system
    app.kubernetes.io/component: ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: auto-shop-backend-service
                port:
                  number: 80
