apiVersion: v1
kind: Secret
metadata:
  name: auto-shop-secrets
  namespace: auto-shop
  labels:
    app.kubernetes.io/name: auto-shop-system
    app.kubernetes.io/part-of: auto-shop-platform
type: Opaque
stringData:
  DB_USER: "seu_usuario_aqui"
  DB_PASSWORD: "sua_senha_segura_aqui"
  SECRET_KEY: "chave_jwt_forte_de_producao_aqui"
  INVERTEXTO_API_TOKEN: "seu_token_invertexto_aqui"
  SMTP_PASSWORD: "sua_senha_smtp_aqui"

