apiVersion: v1
kind: ConfigMap
metadata:
  name: auto-shop-config
  namespace: auto-shop
data:
  APP_ENV: "development"
  APP_BASE_URL: "http://localhost:8000"
  FRONTEND_PUBLIC_URL: "http://localhost:4200"
  CORS_ALLOWED_ORIGINS: "http://localhost:4200"
  CORS_ALLOWED_METHODS: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
  CORS_ALLOWED_HEADERS: "Authorization,Content-Type"
  SECURITY_HSTS_ENABLED: "false"
  SMTP_HOST: "mailhog"
  SMTP_PORT: "1025"
  SMTP_FROM: "noreply@oficina.local"
  SMTP_USE_TLS: "false"
  SMTP_STARTTLS: "false"
  SMTP_REQUIRE_TLS: "false"
  SKIP_CPF_EXTERNAL_VALIDATION: "true"
