apiVersion: v1
kind: Service
metadata:
  name: auto-shop-backend-service
  namespace: auto-shop
  labels:
    app: auto-shop-backend
    app.kubernetes.io/name: auto-shop-system
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app: auto-shop-backend
  ports:
    - name: http
      port: 80
      targetPort: 8000
